### ISSUE TITLE
Enable open browser possible?

### ISSUE THREAD

**Issue by 573** [jamesnetherton/dockerfiles#1]
Hello @jamesnetherton ,

first thanks for this great collection!

Do you know how to make the "Storage options" in the darktable container work?  
When I try to export selected images to any web service (flickr, picasa and the like) I get open browser not supported.

**Comment by jamesnetherton** [comment]
Hi,

Seems Darktable needs a browser to be present in order to complete authentication with some of these third party services. But, even if I add Firefox, I still get `[flickr] error opening browser: Operation not supported`. I'm not sure why yet.

If I get time, I'll give this image an overhaul. The Darktable version used is way behind the latest available.

**Comment by jamesnetherton** [comment]
This should be fixed now.

I had issues getting Chromium to work so opted for Firefox. The small downside is that it opens an extra tab on first use to capture preferences. This can be ignored, but I'll try to see if this can be avoided in a future release.

I also bumped the base image to use Ubuntu so that we can use a newer version of Darktable.

**Comment by 573** [comment]
@jamesnetherton thanks, this fix and explanation was more than accurate and helped me a lot!
